const D=window.ZABON_DATA;
const key="zabon_state_v1";
let state=JSON.parse(localStorage.getItem(key)||"null")||{page:"home",xp:1250,streak:7,completed:2,saved:[],ui:"en",native:"tg",target:"en",dark:false,daily:30,chat:[]};
const save=()=>localStorage.setItem(key,JSON.stringify(state));
const ui=()=>D.ui[state.ui]||D.ui.en;
function icon(x){return ({home:"⌂",learn:"▣",languages:"◎",ai:"✦",translate:"⇄",dictionary:"⌕",words:"♡",review:"↻",challenges:"◈",achievements:"♛",profile:"●",settings:"⚙"})[x]||"•"}
function nav(){
 const items=["home","learn","languages","ai","translate","dictionary","words","review","challenges","achievements","profile","settings"];
 return `<aside class="sidebar"><div class="brand"><img src="assets/logo.svg"><b>ZAB<span>ON</span></b></div><div class="nav">${items.map(k=>`<button class="${state.page===k?"active":""}" onclick="go('${k}')"><span>${icon(k)}</span>${ui()[k]}</button>`).join("")}</div><div class="side-bottom"><button class="nav" onclick="toggleDark()" style="width:100%;border:1px solid var(--line);border-radius:13px;padding:11px;background:var(--card);color:var(--text)">🌙 ${state.dark?"Light":"Dark"} mode</button></div></aside>`;
}
function top(){return `<header class="topbar"><strong>${ui()[state.page]||"ZABON"}</strong><div class="top-actions"><button class="iconbtn" onclick="go('settings')">⚙</button><button class="avatar" onclick="go('profile')">JF</button></div></header>`}
function bottom(){return `<nav class="bottomnav">${["home","learn","ai","translate","profile"].map(k=>`<button class="${state.page===k?"active":""}" onclick="go('${k}')"><b>${icon(k)}</b>${ui()[k]}</button>`).join("")}</nav>`}
function layout(body){return `<div class="app">${nav()}<main class="main">${top()}<div class="content">${body}</div></main>${bottom()}<div id="toast" class="toast"></div></div>`}
function home(){
 const pct=Math.min(100,Math.round(state.completed/30*100));
 return `<section class="hero"><div><div class="eyebrow">ZABON · AI LANGUAGE ACADEMY</div><h1>Learn languages.<br>Understand the world. 🌍</h1><p>A global learning platform for vocabulary, grammar, conversation, translation and daily practice — designed to grow with you from A1 to C2.</p><button class="btn light" onclick="go('learn')">Continue learning →</button></div><div style="min-width:190px;align-self:center"><div style="font-size:52px;font-weight:800">A1</div><div>Current level</div><div class="progress" style="margin-top:15px;background:#ffffff40"><i style="width:${pct}%;background:#fff"></i></div><small>${state.completed}/30 lessons</small></div></section>
<div class="grid"><div class="stat"><small>⚡ XP</small><strong>${state.xp.toLocaleString()}</strong><span class="badge">Level ${Math.floor(state.xp/500)+1}</span></div><div class="stat"><small>🔥 Streak</small><strong>${state.streak} days</strong><span style="color:var(--muted)">Keep going</span></div><div class="stat"><small>📚 Lessons</small><strong>${state.completed}/30</strong><span style="color:var(--muted)">30-day path</span></div><div class="stat"><small>❤️ Saved words</small><strong>${state.saved.length}</strong><span style="color:var(--muted)">My vocabulary</span></div></div>
<div class="section-head"><div><h2>Today's path</h2><p>Small progress every day becomes fluency.</p></div><button class="btn" onclick="startLesson()">Start lesson</button></div>
<div class="card"><div style="display:flex;justify-content:space-between"><b>Day ${state.completed+1} · ${D.course[Math.min(state.completed,29)][0]}</b><span>${Math.min(100,state.completed/30*100).toFixed(0)}%</span></div><p style="color:var(--muted)">${D.course[Math.min(state.completed,29)][1]}</p><div class="progress"><i style="width:${pct}%"></i></div></div>`;
}
function learn(){
 return `<div class="section-head"><div><h2>30-Day Language Path</h2><p>A1 foundation with vocabulary, grammar, listening, speaking and review.</p></div><span class="badge">A1 → A2</span></div><div class="lesson-grid">${D.course.map((l,i)=>`<article class="card lesson"><div class="num">${i+1}</div><h3>${l[0]}</h3><p>${l[1]}<br><em>${l[2]}</em></p><div class="meta"><span>${i<state.completed?"✓ Completed":"• 50 XP"}</span><span>${i<state.completed?"100%":"0%"}</span></div><div class="progress"><i style="width:${i<state.completed?100:0}%"></i></div><button class="btn" style="margin-top:14px;width:100%" onclick="completeLesson(${i})">${i<state.completed?"Review":"Start"}</button></article>`).join("")}</div>`;
}
function languages(){
 return `<div class="section-head"><div><h2>Choose your languages 🌎</h2><p>Native and target languages can be changed anytime.</p></div></div><div class="cards"><div class="card"><b>Native language</b><select class="input" style="margin-top:12px" onchange="state.native=this.value;save();render()">${D.languages.map(x=>`<option value="${x.id}" ${state.native===x.id?"selected":""}>${x.flag} ${x.native}</option>`).join("")}</select></div><div class="card"><b>Learning language</b><select class="input" style="margin-top:12px" onchange="state.target=this.value;save();render()">${D.languages.map(x=>`<option value="${x.id}" ${state.target===x.id?"selected":""}>${x.flag} ${x.name}</option>`).join("")}</select></div></div><div class="section-head"><div><h2>Available languages</h2></div></div><div class="language-grid">${D.languages.map(x=>`<button class="lang" onclick="state.target='${x.id}';save();toast('Learning ${x.name}');render()"><span style="font-size:28px">${x.flag}</span><b>${x.name}</b><small>${x.native}</small></button>`).join("")}</div>`;
}
function ai(){
 const msgs=state.chat.length?state.chat.map(m=>`<div class="msg ${m.r}">${m.t}</div>`).join(""):`<div class="msg ai">👋 Hi! I'm your ZABON AI Tutor. Ask me about grammar, vocabulary, translation, or start a conversation in your target language.</div>`;
 return `<div class="cards"><div class="card chat"><div class="messages">${msgs}</div><div class="chatbar"><input id="aiInput" class="input" placeholder="Write in ${D.languages.find(x=>x.id===state.target)?.name||"English"}..." onkeydown="if(event.key==='Enter')sendAI()"><button class="btn" onclick="sendAI()">Send</button></div></div><div class="card"><h3>🤖 AI Tutor</h3><p style="color:var(--muted);line-height:1.7">Personalized practice based on your level, mistakes, saved words and learning history.</p><div class="word-list"><button class="word" onclick="quickAI('Correct my sentence and explain the mistake.')">✍️ Correct my sentence <b>→</b></button><button class="word" onclick="quickAI('Give me 5 A1 vocabulary words.')">🧠 Vocabulary practice <b>→</b></button><button class="word" onclick="quickAI('Start a simple conversation with me.')">💬 Conversation <b>→</b></button></div><p class="badge" style="margin-top:15px">Demo AI mode</p><small style="display:block;color:var(--muted);margin-top:8px">Connect an AI API later for real model responses. No fake API is claimed here.</small></div></div>`;
}
function translate(){
 return `<div class="card"><div class="toolhead"><div><b>AI Translator</b><div style="color:var(--muted);font-size:13px">Translation architecture ready for a real provider.</div></div><button class="iconbtn" onclick="swapLang()">⇄</button></div><div class="translate-box"><div><select id="src" class="input">${D.languages.map(x=>`<option value="${x.id}" ${state.native===x.id?"selected":""}>${x.flag} ${x.name}</option>`).join("")}</select><textarea id="srcText" class="input" style="margin-top:10px" placeholder="Type text to translate..."></textarea></div><div><select id="dst" class="input">${D.languages.map(x=>`<option value="${x.id}" ${state.target===x.id?"selected":""}>${x.flag} ${x.name}</option>`).join("")}</select><div id="translationOutput" class="output">Your translation will appear here.</div></div></div><div style="display:flex;gap:9px;margin-top:15px"><button class="btn" onclick="translateDemo()">Translate</button><button class="btn ghost" onclick="document.getElementById('srcText').value='';document.getElementById('translationOutput').textContent='Your translation will appear here.'">Clear</button></div><small style="display:block;color:var(--muted);margin-top:12px">Demo mode uses the built-in phrase set. Real unrestricted translation requires a translation API and server-side secret protection.</small></div>`;
}
function dictionary(){
 return `<div class="card"><div class="toolhead"><h2 style="margin:0">Dictionary</h2><input id="dictSearch" class="input" style="max-width:300px" placeholder="Search a word..." oninput="renderDict()"></div><div id="dictResults" class="word-list"></div></div>`;
}
function renderDict(){
 const q=(document.getElementById("dictSearch")?.value||"").toLowerCase();
 const arr=D.words.filter(w=>w.join(" ").toLowerCase().includes(q));
 document.getElementById("dictResults").innerHTML=arr.map((w,i)=>`<div class="word"><div><b>${w[0]}</b><span style="color:var(--muted)"> — ${w[1]}</span><small style="display:block;color:var(--muted)">${w[2]} · example: I use “${w[0]}” every day.</small></div><button class="btn" onclick="saveWord(${i})">${state.saved.includes(w[0])?"Saved":"Save"}</button></div>`).join("")||"<p style='color:var(--muted)'>No words found.</p>";
}
function words(){
 const arr=D.words.filter(w=>state.saved.includes(w[0]));
 return `<div class="section-head"><div><h2>My Words ❤️</h2><p>Save vocabulary and review it regularly.</p></div><span class="badge">${arr.length} saved</span></div><div class="card">${arr.length?`<div class="word-list">${arr.map(w=>`<div class="word"><div><b>${w[0]}</b><span style="color:var(--muted)"> — ${w[1]}</span><small style="display:block;color:var(--muted)">${w[2]}</small></div><button class="iconbtn" onclick="removeWord('${w[0]}')">×</button></div>`).join("")}</div>`:`<div style="text-align:center;padding:45px;color:var(--muted)">Your saved vocabulary will appear here. Open the Dictionary and save your first word.</div>`}</div>`;
}
function review(){return `<div class="card"><div class="eyebrow">DAILY REVIEW</div><h2>Spaced repetition</h2><p style="color:var(--muted);line-height:1.7">Review saved vocabulary, weak words and recent mistakes. Your progress is stored locally on this device.</p><div class="grid"><div class="stat"><small>Due today</small><strong>${Math.max(5,state.saved.length)}</strong></div><div class="stat"><small>Mastered</small><strong>${Math.min(state.saved.length,3)}</strong></div><div class="stat"><small>Accuracy</small><strong>84%</strong></div><div class="stat"><small>XP reward</small><strong>+30</strong></div></div><button class="btn" style="margin-top:20px" onclick="state.xp+=30;save();toast('+30 XP — review complete!')">Start review</button></div>`}
function challenges(){return `<div class="cards"><div class="card"><span class="badge">DAILY · +100 XP</span><h2>Translate 10 sentences</h2><p style="color:var(--muted)">Complete a focused translation challenge today.</p><button class="btn" onclick="state.xp+=100;save();toast('+100 XP challenge completed!')">Complete challenge</button></div><div class="card"><span class="badge">SPEAKING · +40 XP</span><h2>Speak for 60 seconds</h2><p style="color:var(--muted)">Describe your day in your target language.</p><button class="btn" onclick="state.xp+=40;save();toast('+40 XP speaking practice!')">Practice</button></div></div>`}
function achievements(){let a=[["🎯","First Lesson",state.completed>0],["🔥","7 Day Streak",state.streak>=7],["📚","30 Day Streak",state.streak>=30],["💯","100 Words",state.saved.length>=100],["💬","First Conversation",state.chat.length>0],["🌍","Polyglot",state.target!=="en"||state.native!=="en"],["⚡","Speed Learner",state.completed>=10],["👑","ZABON Master",state.completed>=30]];return `<div class="achievement-grid">${a.map(x=>`<div class="card achievement ${x[2]?"":"locked"}"><div class="emoji">${x[0]}</div><h3>${x[1]}</h3><small>${x[2]?"Unlocked":"Locked"}</small></div>`).join("")}</div>`}
function profile(){return `<div class="profile"><div class="card profile-card"><div class="bigavatar">JF</div><h2>JABORZODA FAYZALI</h2><p style="color:var(--muted)">ZABON learner</p><span class="badge">Level ${Math.floor(state.xp/500)+1}</span></div><div class="card"><h2>Learning statistics</h2><div class="grid"><div class="stat"><small>XP</small><strong>${state.xp}</strong></div><div class="stat"><small>Streak</small><strong>${state.streak} 🔥</strong></div><div class="stat"><small>Lessons</small><strong>${state.completed}</strong></div><div class="stat"><small>Words</small><strong>${state.saved.length}</strong></div></div></div></div>`}
function settings(){return `<div class="cards"><div class="card"><h2>Settings</h2><div class="settings-row"><span>Interface language</span><select class="input" style="width:auto" onchange="state.ui=this.value;save();render()"><option value="en" ${state.ui==="en"?"selected":""}>English</option><option value="ru" ${state.ui==="ru"?"selected":""}>Русский</option><option value="tg" ${state.ui==="tg"?"selected":""}>Тоҷикӣ</option></select></div><div class="settings-row"><span>Dark mode</span><button class="toggle ${state.dark?"on":""}" onclick="toggleDark()"><i></i></button></div><div class="settings-row"><span>Daily goal</span><select class="input" style="width:auto" onchange="state.daily=+this.value;save();toast('Daily goal updated')">${[5,10,15,20,30].map(n=>`<option ${state.daily===n?"selected":""}>${n}</option>`).join("")}</select></div></div><div class="card"><h2>Account & privacy</h2><p style="color:var(--muted);line-height:1.7">Authentication, cloud sync, payments and account deletion require a secure backend. This GitHub Pages edition intentionally does not pretend those systems are live.</p><span class="badge">Static Demo / Local Data</span></div></div>`}
function startLesson(){completeLesson(state.completed);go("learn")}
function completeLesson(i){if(i>=state.completed)return toast("This lesson is already completed.");state.completed=Math.min(30,state.completed+1);state.xp+=50;state.streak=Math.max(1,state.streak);save();toast("Lesson completed · +50 XP 🎉");render()}
function saveWord(i){let w=D.words[i][0];if(!state.saved.includes(w)){state.saved.push(w);state.xp+=5;save();toast(`Saved “${w}” · +5 XP`)}renderDict()}
function removeWord(w){state.saved=state.saved.filter(x=>x!==w);save();render()}
function sendAI(){let el=document.getElementById("aiInput"),t=el.value.trim();if(!t)return;state.chat.push({r:"user",t});state.chat.push({r:"ai",t:"Demo Tutor: Great question! In the full ZABON backend, I would analyze your level, correct your grammar, explain the mistake, and adapt the next exercise. For now, try writing one simple sentence in your target language."});state.xp+=20;save();render()}
function quickAI(t){state.chat.push({r:"user",t});state.chat.push({r:"ai",t:"Demo Tutor: "+(t.includes("vocabulary")?"Here are 5 practice words: hello · family · work · travel · tomorrow.":"Send me your sentence and I’ll show how a real ZABON AI tutor would structure the correction." )});save();render()}
function translateDemo(){let t=document.getElementById("srcText").value.trim();let o=document.getElementById("translationOutput");if(!t)return o.textContent="Type something first.";let known={"hello":"салом","thank you":"раҳмат","good morning":"субҳ ба хайр","water":"об","family":"оила","friend":"дӯст","work":"кор","home":"хона","today":"имрӯз","tomorrow":"фардо"};let low=t.toLowerCase();o.textContent=known[low]||"Demo translation: connect a real translation provider for unrestricted multilingual translation."}
function swapLang(){let s=document.getElementById("src"),d=document.getElementById("dst");if(s&&d){let x=s.value;s.value=d.value;d.value=x}}
function toggleDark(){state.dark=!state.dark;document.body.classList.toggle("dark",state.dark);save();render()}
function go(p){state.page=p;save();render();window.scrollTo(0,0)}
function toast(t){let e=document.getElementById("toast");if(!e)return;e.textContent=t;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),2200)}
function render(){
 document.body.classList.toggle("dark",state.dark);
 let body={home,learn,languages,ai,translate,dictionary,words,review,challenges,achievements,profile,settings}[state.page]?.()||home();
 document.getElementById("app").innerHTML=layout(body);
 if(state.page==="dictionary")renderDict();
}
render();
